version: 2.1

jobs:
  run-python-script:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      - run:
          name: test step
          command: echo "hello world shell"

      - run:
          name: Run Python script
          command: python test.py

workflows:
  version: 2
  run-python-workflow:
    jobs:
      - run-python-script
